In [141]:
import pandas as pd

In [142]:
df = pd.read_csv(r"dataset\BBC News Train.csv")
print(f'''
      Shape: {df.shape}
      Columns: {df.columns.tolist()}
      Category column values: {df['Category'].unique().tolist()}
''')

      Shape: (1490, 3)
      Columns: ['ArticleId', 'Text', 'Category']
      Category column values: ['business', 'tech', 'politics', 'sport', 'entertainment']

In [143]:
tech_data = df[df.Category=='tech']
print(tech_data.shape)
tech_data.head()

(261, 3)

    ArticleId                                               Text Category
3        1976  lifestyle  governs mobile choice  faster  bett...     tech
19       1552  moving mobile improves golf swing a mobile pho...     tech
24        405  bt boosts its broadband packages british telec...     tech
26        702  peer-to-peer nets  here to stay  peer-to-peer ...     tech
30       1951  pompeii gets digital make-over the old-fashion...     tech

In [144]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\gaura\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [145]:
tech_data = tech_data.copy()

tech_data["num_sent"] = tech_data["Text"].apply(lambda x: len(sent_tokenize(x)))
filtered_data = tech_data[tech_data['Text'].str.contains('microsoft',case=False,na=False)]

filtered_data = filtered_data.copy()
filtered_data = filtered_data[(filtered_data["num_sent"] <= 15)]
filtered_data = filtered_data.drop_duplicates(subset=['Text'], keep='first')

filtered_data.to_csv(r'filtered_data.csv',index=False)

In [146]:
print(filtered_data.shape)
filtered_data.sort_values('num_sent')

(9, 4)

,ArticleId,Text,Category,num_sent
301,428,microsoft takes on desktop search microsoft ha...,tech,10
651,1615,microsoft seeking spyware trojan microsoft is ...,tech,10
428,69,microsoft gets the blogging bug software giant...,tech,13
509,2042,virus poses as christmas e-mail security firms...,tech,13
861,184,xbox power cable fire fear microsoft has sai...,tech,13
1179,728,anti-spam laws bite spammer hard the net s sel...,tech,13
48,277,halo 2 sells five million copies microsoft is ...,tech,14
589,1604,joke e-mail virus tricks users a virus that di...,tech,15
1305,1004,microsoft releases bumper patches microsoft ha...,tech,15