In [120]:
import pandas as pd

In [121]:
df = pd.read_csv(r"dataset\BBC News Train.csv")
print(f'''
      Shape: {df.shape}
      Columns: {df.columns.tolist()}
      Category column values: {df['Category'].unique().tolist()}
''')

      Shape: (1490, 3)
      Columns: ['ArticleId', 'Text', 'Category']
      Category column values: ['business', 'tech', 'politics', 'sport', 'entertainment']

In [122]:
tech_data = df[df.Category=='tech']
print(tech_data.shape)
tech_data.head()

(261, 3)

    ArticleId                                               Text Category
3        1976  lifestyle  governs mobile choice  faster  bett...     tech
19       1552  moving mobile improves golf swing a mobile pho...     tech
24        405  bt boosts its broadband packages british telec...     tech
26        702  peer-to-peer nets  here to stay  peer-to-peer ...     tech
30       1951  pompeii gets digital make-over the old-fashion...     tech

In [123]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\gaura\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [124]:
tech_data = tech_data.copy()
tech_data["num_sent"] = tech_data["Text"].apply(lambda x: len(sent_tokenize(x)))

filtered = tech_data[(tech_data["num_sent"] >= 6) & (tech_data["num_sent"] <= 10)]

In [125]:
final_docs = filtered.sample(n=3, random_state=42)
print(f'Total sentences: {final_docs.num_sent.sum()}')
final_docs

Total sentences: 25

,ArticleId,Text,Category,num_sent
301,428,microsoft takes on desktop search microsoft ha...,tech,10
686,37,gamers snap up new sony psp gamers have bought...,tech,8
268,474,broadband steams ahead in the us more and more...,tech,7