In [12]:
import pandas as pd

## Reading the clustered document

In [13]:
df = pd.read_csv(r"dataset\output\sentences_with_hdbscan_clusters.csv")
print(df.shape)
df.head()

(116, 8)

,article_id,sentence,pub_date,emb_index,umap_x,umap_y,hdb_cluster,hdb_prob
0,184,a follow-up to xbox is expected to released at...,"Fri, 25 Mar 2022 10:33:43 GMT",87,2.547743,14.610622,2,1.000000
1,1004,a further patch fixes a hole in media player w...,"Mon, 04 Apr 2022 01:51:59 GMT",112,4.934868,15.862391,0,1.000000
2,69,according to blog analysis firm technorati the...,"Mon, 14 Mar 2022 17:55:20 GMT",35,1.029510,12.818722,3,1.000000
3,277,according to microsoft nine out of 10 xbox liv...,"Sun, 06 Mar 2022 21:55:52 GMT",2,2.268620,14.766386,2,0.963922
4,728,according to microsoft the messages were sent ...,"Fri, 01 Apr 2022 20:58:12 GMT",93,4.430966,12.671751,-1,0.000000

In [14]:
print(f"Total columns: {len(df.columns)}")
print(f"Column names: {df.columns.tolist()}")

Total columns: 8
Column names: ['article_id', 'sentence', 'pub_date', 'emb_index', 'umap_x', 'umap_y', 'hdb_cluster', 'hdb_prob']

In [15]:
clusters = sorted([c for c in df['hdb_cluster'].unique().tolist() if c > -1])
print(clusters)

[0, 1, 2, 3, 4]

In [16]:
CLUSTER_NUM = clusters[0]

filtered_df = df[df['hdb_cluster']==CLUSTER_NUM].copy()
filtered_df = filtered_df[["article_id","sentence","pub_date","hdb_cluster"]]

In [17]:
print(f"CLUSTER-{CLUSTER_NUM} Total sentences: {len(filtered_df)}")
filtered_df.head(10)

CLUSTER-0 Total sentences: 54

,article_id,sentence,pub_date,hdb_cluster
1,1004,a further patch fixes a hole in media player w...,"Mon, 04 Apr 2022 01:51:59 GMT",0
7,2042,anti-virus firm sophos said that 10% of the e-...,"Thu, 17 Mar 2022 01:08:07 GMT",0
8,1604,anti-virus firms are issuing high-level warnin...,"Fri, 18 Mar 2022 00:18:09 GMT",0
9,2042,anti-virus firms speculate that this multiling...,"Thu, 17 Mar 2022 01:08:07 GMT",0
10,1604,anti-virus firms urged users to be wary of une...,"Fri, 18 Mar 2022 00:18:09 GMT",0
12,1604,as well as plundering microsoft outlook for e-...,"Fri, 18 Mar 2022 00:18:09 GMT",0
13,1604,bbc news online has received five warnings abo...,"Fri, 18 Mar 2022 00:18:09 GMT",0
14,1604,black spider said it had stopped more than 1 m...,"Fri, 18 Mar 2022 00:18:09 GMT",0
21,1615,earlier this week microsoft said it would buy ...,"Sun, 20 Mar 2022 02:51:19 GMT",0
22,1604,finnish company f-secure gave the virus its se...,"Fri, 18 Mar 2022 00:18:09 GMT",0

## Formatting & Sorting the ***pub_date*** column

In [18]:
import dateparser
import os

In [19]:
OUTPUT_DIR = r"dataset\output\temporal_meta"

In [20]:
for files in os.listdir(OUTPUT_DIR):
    os.remove(os.path.join(OUTPUT_DIR,files))

In [21]:
for c in clusters:
    filtered_df = df[df['hdb_cluster']==c].copy()
    filtered_df = filtered_df[["article_id","sentence","pub_date","hdb_cluster"]]
    print(f"CLUSTER-{c} Total sentences: {len(filtered_df)}")
    
    date_col = "pub_date"

    filtered_df['formatted_date'] =  filtered_df[date_col].apply(
        lambda x: dateparser.parse(x, settings={
            "TIMEZONE": "UTC", 
            "RETURN_AS_TIMEZONE_AWARE": True
            })
    )
    
    sorted_df = filtered_df.sort_values(['formatted_date'])
    result_df = sorted_df
    
    output_path = os.path.join(OUTPUT_DIR,f"cluster{c}_temporalSort_metaData.csv")
    result_df.to_csv(output_path,index=False)

CLUSTER-0 Total sentences: 54
CLUSTER-1 Total sentences: 12
CLUSTER-2 Total sentences: 22
CLUSTER-3 Total sentences: 11
CLUSTER-4 Total sentences: 7

In [22]:
result_df.head()

,article_id,sentence,pub_date,hdb_cluster,formatted_date
11,428,apple will release a similar search system for...,"Fri, 11 Mar 2022 22:16:48 GMT",4,2022-03-11 22:16:48+00:00
25,428,google has already released a desktop tool.,"Fri, 11 Mar 2022 22:16:48 GMT",4,2022-03-11 22:16:48+00:00
70,428,search giant google launched its desktop searc...,"Fri, 11 Mar 2022 22:16:48 GMT",4,2022-03-11 22:16:48+00:00
72,428,small firms such as blinkx copernic enfish x1 ...,"Fri, 11 Mar 2022 22:16:48 GMT",4,2022-03-11 22:16:48+00:00
77,428,the beta program only works on pcs running win...,"Fri, 11 Mar 2022 22:16:48 GMT",4,2022-03-11 22:16:48+00:00