In [54]:
import pandas as pd

In [55]:
original_df = pd.read_csv(r"dataset\BBC News Train.csv")
original_df.head()

   ArticleId                                               Text  Category
0       1833  worldcom ex-boss launches defence lawyers defe...  business
1        154  german business confidence slides german busin...  business
2       1101  bbc poll indicates economic gloom citizens in ...  business
3       1976  lifestyle  governs mobile choice  faster  bett...      tech
4        917  enron bosses in $168m payout eighteen former e...  business

In [56]:
df = pd.read_csv(r"dataset\output\sentences_with_hdbscan_clusters.csv")
cluster_num = 5
df = df[df['hdb_cluster']==cluster_num]
print(f"total sentences: {len(df)}")
df

total sentences: 5

,article_id,sentence,emb_index,umap_x,umap_y,hdb_cluster,hdb_prob
4,1680,the message asks recipients to click on the at...,4,9.990837,4.950269,5,1.0
5,1680,but rather than being a questionnaire the atta...,5,9.975196,5.136771,5,1.0
7,1680,users are warned never to open attachment from...,7,10.152564,4.992000,5,1.0
17,2042,to be infected users must open up the attachme...,17,9.992801,5.181167,5,1.0
43,1604,users will be infected if they open the attach...,43,10.090630,5.090462,5,1.0

In [57]:
for i in df.sentence:
    print("Sentence:",i)

Sentence: the message asks recipients to click on the attachment and answer some questions about their internet use.
Sentence: but rather than being a questionnaire the attachment contains a virus that infects the recipient s computer according to the agency.
Sentence: users are warned never to open attachment from unsolicited e-mails or from people they do not know.
Sentence: to be infected users must open up the attachment travelling with the message which bears the code for the malicious bug.
Sentence: users will be infected if they open the attachment that travels with the e-mail.