In [1]:
import pandas as pd

## Balanced Dataset

In [8]:
df_bal = pd.read_csv(r"dataset\preprocessing\prePro-news_balanced.csv")
print(f'''
Shape: {df_bal.shape}
Columns: {df_bal.columns.tolist()}

{df_bal.category.value_counts()}
''')
df_bal.head()

Shape: (1291, 5)
Columns: ['content_id', 'sentence', 'published_date', 'timestamp', 'category']

Gadgets    883
5G         408
Name: category, dtype: int64

,content_id,sentence,published_date,timestamp,category
0,1442420,"Until now, the AirPods Pro were all about keep...",2024-09-17,1726531200,Gadgets
1,1442420,Apple says the latest AirPods Pro 2 can be use...,2024-09-17,1726531200,Gadgets
2,1442420,"Pending approval by regulatory authorities, th...",2024-09-17,1726531200,Gadgets
3,1442420,The company is also planning to integrate a he...,2024-09-17,1726531200,Gadgets
4,1442420,"If the feature takes hold, Apple could use it ...",2024-09-17,1726531200,Gadgets

## Un-balanced Dataset

In [9]:
df_bal = pd.read_csv(r"dataset\preprocessing\prePro-news_filtered.csv")
print(f'''
Shape: {df_bal.shape}
Columns: {df_bal.columns.tolist()}

{df_bal.category.value_counts()}
''')
df_bal.head()

Shape: (5120, 5)
Columns: ['content_id', 'sentence', 'published_date', 'timestamp', 'category']

Gadgets    4712
5G          408
Name: category, dtype: int64

,content_id,sentence,published_date,timestamp,category
0,1808882,CelcomDigi has refreshed its Postpaid 5G plans...,2026-02-05,1770249600,5G
1,1808882,The company said the newest addition is the Po...,2026-02-05,1770249600,5G
2,1808882,The plan also includes access to streaming ser...,2026-02-05,1770249600,5G
3,1808882,Other unlimited data with uncapped speed plans...,2026-02-05,1770249600,5G
4,1808882,The unlimited quota is subject to the company'...,2026-02-05,1770249600,5G