In [3]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer

In [4]:
model = SentenceTransformer('all-MiniLM-L6-v2')

## Balanced Dataset

In [5]:
df_bal = pd.read_csv(r"dataset\preprocessing\prePro-news_balanced.csv")
print(f'''
Shape: {df_bal.shape}
Columns: {df_bal.columns.tolist()}

{df_bal.category.value_counts()}
''')
df_bal.head()

Shape: (1291, 5)
Columns: ['content_id', 'sentence', 'published_date', 'timestamp', 'category']

Gadgets    883
5G         408
Name: category, dtype: int64

,content_id,sentence,published_date,timestamp,category
0,1442420,"Until now, the AirPods Pro were all about keep...",2024-09-17,1726531200,Gadgets
1,1442420,Apple says the latest AirPods Pro 2 can be use...,2024-09-17,1726531200,Gadgets
2,1442420,"Pending approval by regulatory authorities, th...",2024-09-17,1726531200,Gadgets
3,1442420,The company is also planning to integrate a he...,2024-09-17,1726531200,Gadgets
4,1442420,"If the feature takes hold, Apple could use it ...",2024-09-17,1726531200,Gadgets

## Sentence Embeddings (Balanced)

In [7]:
sentences = df_bal['sentence'].tolist()

sentence_embeddings = model.encode(sentences, show_progress_bar=True)

Batches:   0%|          | 0/41 [00:00<?, ?it/s]

In [8]:
print("Sentence Embedding Shape:", sentence_embeddings.shape)

Sentence Embedding Shape: (1291, 384)

array([ 1.12613803e-02, -4.27247472e-02,  6.09275140e-02,  2.61732563e-02,
        9.54781566e-03, -4.95798513e-02,  5.90258092e-02, -8.61782208e-02,
       -4.63473052e-02,  3.29425484e-02,  3.79321091e-02,  6.41812757e-02,
       -2.55513284e-02, -6.94884732e-02, -2.33524498e-02,  5.16863093e-02,
        9.38164666e-02,  4.03177254e-02, -2.74585430e-02, -1.93251874e-02,
       -6.08029440e-02,  3.38467136e-02,  1.20218121e-01,  1.09280035e-01,
       -2.93970620e-03, -6.53616560e-04,  1.02617145e-02, -6.92559257e-02,
       -1.52990632e-02,  7.17318757e-03,  2.52705142e-02,  1.95877999e-03,
        1.93117242e-02, -2.03704685e-02, -1.46132875e-02, -1.07932843e-01,
        5.31684831e-02,  6.45445660e-02,  5.61067313e-02, -7.22459145e-03,
       -1.44273797e-02,  5.03298156e-02, -7.52890781e-02, -7.19192624e-02,
       -5.91462106e-02, -2.74630319e-02, -1.65997948e-02, -1.02161907e-01,
        8.34512040e-02,  9.97222215e-02,  3.83578166e-02, -7.83942565e-02,
        4.22392972e-02, -1.04063824e-02,  1.73455682e-02,  5.10626361e-02,
        7.25580081e-02,  1.93017181e-02, -3.39527465e-02,  1.62520893e-02,
        4.03755680e-02, -6.04235306e-02, -6.54793519e-04, -3.40979099e-02,
       -3.27955522e-02, -1.09698670e-03, -3.81545164e-02,  7.03432262e-02,
        6.18785061e-02,  3.59088145e-02, -1.24600362e-02,  8.49602520e-02,
       -9.00950469e-03, -1.80702284e-02,  8.10958892e-02,  1.00666463e-01,
       -1.26391230e-03, -5.87448180e-02,  5.28677218e-02,  9.72831398e-02,
       -9.04467702e-03, -5.97216897e-02,  6.96031004e-03, -9.02741477e-02,
        2.34370343e-02, -6.48995191e-02,  2.23990846e-02, -9.36629698e-02,
       -5.01287766e-02,  1.44434301e-03, -7.59633705e-02, -2.76812557e-02,
        7.26035738e-04,  1.43728061e-02,  2.34868396e-02, -5.97257502e-02,
        1.38178244e-02,  3.83950956e-02,  4.66632396e-02, -3.78194042e-02,
        4.53588925e-02, -2.20345911e-02, -2.74450406e-02, -6.73255324e-02,
        5.34304157e-02, -3.09270825e-02, -8.41122195e-02, -5.73661886e-02,
       -4.16986458e-02,  7.21933842e-02,  2.56604701e-02, -5.63869327e-02,
        5.26440442e-02,  2.43034102e-02, -6.02107495e-02,  1.27016887e-01,
       -2.86200978e-02,  6.88869283e-02,  3.29193659e-02, -6.96300641e-02,
       -3.90098523e-03,  3.82559784e-02,  1.67677030e-02, -1.71380565e-02,
       -8.53557140e-04,  3.21065746e-02, -1.15147248e-01,  1.35402678e-33,
        3.00185219e-03, -4.17051055e-02,  1.25414683e-02, -1.76128149e-02,
        2.74706725e-02, -6.46706745e-02, -6.40805215e-02, -3.00178584e-02,
        4.82101701e-02,  4.56267484e-02, -6.31453916e-02, -2.43467744e-02,
        1.52689684e-02, -8.08731318e-02,  5.42344451e-02, -9.48556215e-02,
       -6.54727593e-02,  5.08600362e-02, -4.74513210e-02,  3.41633596e-02,
        2.07594931e-02,  3.38571426e-03,  1.02114184e-02,  1.13772333e-01,
        1.05397873e-01,  7.62357842e-03,  3.34556177e-02, -1.24234539e-02,
       -3.59086022e-02,  3.96284880e-03, -6.52271658e-02,  6.05086088e-02,
        5.09615615e-02,  3.32141183e-02,  1.96665730e-02,  2.93613481e-03,
        4.62930202e-02,  1.00376019e-02,  4.98616025e-02, -7.86675289e-02,
       -2.07683025e-03, -2.14366056e-02,  3.72565375e-03, -5.10692075e-02,
        9.67559665e-02,  5.47180101e-02, -4.69470397e-02, -5.09814285e-02,
        7.24607706e-02, -2.36168317e-02, -3.19641754e-02,  9.48472135e-03,
       -4.73903157e-02,  2.35050619e-02, -2.32613534e-02, -7.24602342e-02,
       -7.61507172e-03, -2.12290697e-02, -2.26723645e-02, -3.02370898e-02,
       -1.59418229e-02,  2.33280044e-02,  3.00151724e-02, -5.31055965e-02,
       -6.00166172e-02,  1.02535553e-01, -1.42755210e-02, -1.61578953e-02,
       -7.49184117e-02, -5.62294982e-02,  9.52541269e-03,  1.12769231e-01,
       -2.78016366e-02,  3.82579193e-02, -9.30957496e-02, -2.48094220e-02,
       -7.07820728e-02, -6.84280181e-03,  6.32607490e-02, -4.29388396e-02,
        3.99038196e-03,  8.26491043e-02, -6.59692436e-02,  3.37096564e-02,
        2.24511139e-02, -2.86000613e-02,  6.12375513e-03,  6.30203029e-03,
        4.26247381e-02, -1.47677977e-02,  5.08071715e-03,  3.63611504e-02,
       -3.59416679e-02,  2.62630787e-02, -3.02107614e-02, -2.49550159e-33,
       -9.58321057e-03, -4.07207645e-02, -2.24228892e-02,  1.18425097e-02,
       -5.87782823e-02,  8.01419318e-02,  8.20503607e-02, -2.62628291e-02,
       -5.69987204e-03, -2.97745671e-02,  3.04450262e-02, -9.25693102e-03,
       -3.45239975e-02,  6.44453764e-02, -1.20534739e-02, -9.85509902e-02,
       -8.82612448e-03, -4.10815217e-02,  2.33085752e-02,  8.52132812e-02,
        6.71300571e-03, -4.73792739e-02,  9.15614069e-02, -5.01080118e-02,
       -3.74610387e-02, -5.18081784e-02, -6.12842739e-02,  4.08964939e-02,
        6.54708967e-02, -5.64129092e-02, -3.25200409e-02,  7.10302144e-02,
       -1.98808741e-02, -1.03396038e-02,  6.32846877e-02, -3.17519940e-02,
       -8.76621082e-02, -4.35275584e-02,  4.59287278e-02, -5.62135801e-02,
       -3.09749972e-02,  5.23468927e-02,  1.37909818e-02, -8.18287134e-02,
        1.71049293e-02,  2.31458005e-02, -7.64388666e-02,  2.74604652e-02,
       -3.54504064e-02, -9.75131914e-02,  6.34184107e-03,  6.40109554e-02,
        2.12596077e-03,  2.13294849e-02, -4.24701460e-02,  2.34687291e-02,
       -2.08804291e-02,  5.28643504e-02,  2.49921884e-02,  8.75018479e-04,
       -1.51080741e-02,  3.40433083e-02,  8.55992436e-02, -6.60599321e-02,
       -8.49311799e-02,  1.44714400e-01, -3.81154567e-02,  6.65048212e-02,
        4.52084653e-02, -5.57710510e-03,  4.26202193e-02,  4.88325246e-02,
       -6.19330443e-02,  2.41900310e-02,  4.07293551e-02,  2.56642345e-02,
       -7.35546201e-02, -3.14912014e-02,  3.49663198e-02,  1.51789812e-02,
       -4.05871170e-03,  4.69960012e-02,  1.71221141e-02,  1.14397131e-01,
        8.05657264e-03,  5.06093502e-02, -6.72258884e-02, -2.31728088e-02,
       -3.40497233e-02,  1.04359724e-01,  4.19691578e-03, -2.61264667e-02,
       -4.99024289e-03,  1.12229874e-02, -1.32142687e-02, -3.14419921e-08,
        3.62162329e-02, -2.56802812e-02,  6.74010739e-02, -5.12981080e-02,
        8.46865028e-03, -4.47617024e-02,  2.00612703e-03,  5.48608527e-02,
        1.68588758e-02, -1.80844534e-02,  2.51139551e-02,  1.28768757e-03,
       -2.69633513e-02,  4.81335521e-02,  3.92765217e-02,  5.48724495e-02,
       -7.61291236e-02,  5.63275516e-02,  5.51083824e-03, -8.33668187e-02,
       -5.70421740e-02,  3.80454957e-02, -8.37730169e-02,  1.51580051e-02,
       -3.02553759e-03,  1.83555111e-02,  2.40392121e-03, -1.07104182e-02,
       -5.97787574e-02, -3.56704816e-02,  8.24589562e-03, -3.33387628e-02,
       -9.58641693e-02, -8.92437622e-03, -2.67528966e-02,  5.93915675e-03,
        4.73233052e-02,  7.40664126e-03, -3.61169409e-03,  1.44627029e-02,
       -8.19948688e-02, -8.61428976e-02, -2.09462289e-02,  3.55791934e-02,
        4.63128136e-03, -2.55449321e-02,  1.20772995e-01, -3.38213742e-02,
       -4.78894003e-02,  6.64623231e-02, -5.57380822e-03,  8.56387764e-02,
        4.99867015e-02, -5.84498532e-02,  2.10767165e-02,  4.49210331e-02,
       -3.72139588e-02, -5.99675514e-02, -1.34713531e-01,  6.98588192e-02,
       -4.97703068e-03, -5.92276752e-02,  3.62079665e-02,  1.14542916e-01],
      dtype=float32)

## Un-balanced Dataset

In [6]:
df_unbal = pd.read_csv(r"dataset\preprocessing\prePro-news_filtered.csv")
print(f'''
Shape: {df_unbal.shape}
Columns: {df_unbal.columns.tolist()}

{df_unbal.category.value_counts()}
''')
df_unbal.head()

Shape: (5120, 5)
Columns: ['content_id', 'sentence', 'published_date', 'timestamp', 'category']

Gadgets    4712
5G          408
Name: category, dtype: int64

,content_id,sentence,published_date,timestamp,category
0,1808882,CelcomDigi has refreshed its Postpaid 5G plans...,2026-02-05,1770249600,5G
1,1808882,The company said the newest addition is the Po...,2026-02-05,1770249600,5G
2,1808882,The plan also includes access to streaming ser...,2026-02-05,1770249600,5G
3,1808882,Other unlimited data with uncapped speed plans...,2026-02-05,1770249600,5G
4,1808882,The unlimited quota is subject to the company'...,2026-02-05,1770249600,5G