In [114]:
import pandas as pd
import numpy as np

In [115]:
episode_df = pd.read_csv(r"dataset\fineTuned\top10_episodes.csv",index_col=0)
embeddings = np.load(r"dataset\notFineTuned\embeddings\balanced_episode_embeddings.npy")
episode_df['published_date'] = pd.to_datetime(episode_df['published_date'])
episode_df = episode_df.reset_index()

In [116]:
print("Number of sentences:", len(episode_df))
episode_df.head()

Number of sentences: 337

,orig_index,content_id,sentence,published_date,category,timestamp,episode,t
0,0,1442420,"Until now, the AirPods Pro were all about keep...",2024-09-17,Gadgets,2024-09-17,18,208
1,1,1442420,Apple says the latest AirPods Pro 2 can be use...,2024-09-17,Gadgets,2024-09-17,18,208
2,3,1442420,The company is also planning to integrate a he...,2024-09-17,Gadgets,2024-09-17,18,208
3,5,1442420,At Apple's annual September product launch eve...,2024-09-17,Gadgets,2024-09-17,18,208
4,7,1442420,The new AirPods also have a slightly modified ...,2024-09-17,Gadgets,2024-09-17,18,208

In [117]:
indices = episode_df["orig_index"].values
episode_embeddings = embeddings[indices]

## Clustering within episode to find events

In [118]:
import hdbscan

In [119]:
clusterer = hdbscan.HDBSCAN(
    min_cluster_size=4,
    metric='euclidean',
    prediction_data=True
) 

event_labels = clusterer.fit_predict(episode_embeddings)

c:\Users\gaura\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
c:\Users\gaura\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [120]:
episode_df["event_id"] = event_labels

In [121]:
print("Unique event IDs:", set(event_labels))
print("Number of clusters (excluding -1):", len(set(event_labels)) - (1 if -1 in event_labels else 0))
print("Noise points:", list(event_labels).count(-1))

Unique event IDs: {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, -1}
Number of clusters (excluding -1): 10
Noise points: 31

In [122]:
episode_df = episode_df[episode_df["event_id"] != -1].copy()

In [123]:
event_counts = episode_df["event_id"].value_counts()

print(event_counts)

4    95
0    35
8    35
6    31
2    25
1    21
3    20
7    15
9    15
5    14
Name: event_id, dtype: int64

In [124]:
valid_events = event_counts[event_counts >= 3].index

episode_df = episode_df[episode_df["event_id"].isin(valid_events)].copy()
episode_df.shape

(306, 9)

In [125]:
episode_df = episode_df.sort_values(by=["event_id", "published_date"])

In [126]:
for event in episode_df["event_id"].unique():
    print("\n======================")
    print(f"Event ID: {event}")
    print("======================")
    
    samples = episode_df[episode_df["event_id"] == event]["sentence"].head(5)
    
    for s in samples:
        print("-", s)

======================
Event ID: 0
======================
- Children are developing nearsightedness earlier in life, and while looking too long and too close at phones and tablets may play a role, the answer is not that simple, according to a Connecticut paediatric ophthalmologist in the US.
- “We are seeing an increased rate of myopia over the last, I would say, 20 years or so, and it is projected to increase,” said Dr Majida Gaffar, division head of ophthalmology at Connecticut Children’s Medical Center.
- “It’s definitely something that ophthalmologists and optometrists are looking at to slow the Myopia affects about 5% of preschoolers, 9% of school-aged children and 30% of teens, according to While there is no cause for myopia, the formal name for nearsightedness, there are correlations, such as “near work and diet ... environmental factors,” Gaffar said.
- Also, the child of someone with myopia is more likely to be nearsighted.
- “I’ll always tell my patients to limit as much as possible, even though they haven’t really found that those are causing myopia,” she said.

======================
Event ID: 1
======================
- This month, many of the 80 million owners of Roku devices, including streaming sticks, set-top boxes and Internet-connected TVs running the company’s streaming software, turned on their Rokus to see a block of text.
- I, the owner of a cheap Roku TV in my bedroom, was among those who got stuck with the screen.
- Unless they agreed, users were blocked from access to the Roku menu and apps, essentially bricking their devices.
- So he came up with a workaround to disconnect his Roku TV from the Internet and use it as a normal TV without Roku’s apps, which include Netflix, Hulu and other streaming services.
- It’s pretty Also this month, Roku announced a security breach involving about 15,000 user accounts.

======================
Event ID: 2
======================
- British fire chiefs and recycling campaigners have warned that fires caused by discarded batteries in electricals are on the rise, causing damage and spikes in air pollution levels.
- According to a study by Material Focus, which leads the Recycle Your Electricals campaign, battery fires in bin lorries and at waste sites have risen by more than 70% since 2022, with more than 1,200 estimated to have occurred last year.
- It said that the steep rise in the number of portable electrical items containing lithium-ion batteries being bought and used by the public was leading to an increased risk of fires, with the study indicating that billion batteries were thrown away last year, including billion containing lithium-ion batteries.
- Found inside most common portable electronics, including laptops, phones, tablets, earpods and vapes, lithium-ion batteries can be crushed or damaged if not recycled and instead end up in bin lorries or waste sites – which can lead to fires.
- Alongside the campaigners, the National Fire Chiefs Council noted that lithium-ion battery fires can be particularly dangerous to the public, waste site workers and firefighters because of the risk of chemical exposure and reigniting as they can generate their own oxygen.

======================
Event ID: 3
======================
- How much would you be willing to spend on a keyboard?
- For the hardcore enthusiasts who gathered during the 2024 edition of the Malaysia Mechanical Keyboard (MYMK) meetup on Oct 28 in Kuala Lumpur, this could range from the low hundreds to the tens of thousands.
- Community member and co-organiser of the meetup, Joshua Zen (also known as ZenTheGeek online), shared that he has collected a total of 12 keyboards, each averaging between RM1,000 to RM1,500 depending on the configuration.
- Of course, these aren’t the run-of-the-mill keyboards you can pick up off the shelf at any mall; most are custom-built through limited group buys, making them highly exclusive, as another production run is rarely guaranteed.
- “The keyboard is a modern, essential tool for the working adults of today.

======================
Event ID: 4
======================
- Meanwhile, Fahmi said that for instance, he had spoken with Kuala Lumpur City Hall (DBKL) to look at how MNOs can adopt not only 5G but also 5G advanced, particularly to realise the idea of smart cities. "A lot of this new technology can be quickly and quite swiftly implemented.
- Malaysia has recorded almost million 5G service subscriptions, representing an adoption rate of as of Jan 31, said Communications Minister Fahmi Fadzil.
- Malaysia has proven to the world that the approach it has taken to build a 5G network is successful after emerging at the top spot globally in the 5G consistency score.
- Ookla, a global leader in network intelligence and connectivity insights, announced today that Malaysia's 5G Consistency Score for Q4 2023 is the global winner amongst countries which had successfully launched 5G commercially
- Describing it as a well-deserved award, Bye noted that although the approach taken by Malaysia in building the network with Digital Nasional Berhad (DNB) was unique and had a lot of sceptics, it however had proven could be successful with the support of the regulatory environment, the ministry and operators. "It has really proven to be something that I think many countries are gonna look at and wonder if that may be a better approach for the way in which they are deploying 5G and advanced technology.

======================
Event ID: 5
======================
- Photos sure do take up a lot of space on our phones and computers.
- When smartphone cameras took over as our main cameras, more storage on the phones became a necessity.
- Remember when your phone only had 8 or 16 gigabytes of storage?
- The new iPhone 16 and Google Pixel 9 Pro have a minimum of 128 GB of storage with options for expanding it up to 256 GB for the Pixel 9 and 512 GB for the iPhone 16.
- The iPhone 16 Pro and Google Pixel 9 Pro models give options up to one terabyte.

======================
Event ID: 6
======================
- In addition, Apple is looking to create a version of its AirPods earbuds that include cameras, letting them better sense the outside world.
- Until now, the AirPods Pro were all about keeping the noise out, but Apple's noise-cancelling earbuds are now going in the opposite direction with a new hearing aid feature.
- Apple says the latest AirPods Pro 2 can be used as "clinical-grade" hearing aids by boosting sounds like voices or certain ambient noises when the feature is turned on.
- The company is also planning to integrate a hearing test into the AirPods, whereby the user taps the screen when they hear a certain frequency.
- At Apple's annual September product launch event in California on Monday, the company also announced a new generation of standard AirPods with active noise cancelling.

======================
Event ID: 7
======================
- Apple Inc rolled out updated versions of the iPad Pro, Vision Pro and entry-level MacBook Pro with the new M5 chip, refreshing the products just ahead of the all-important holiday season.
- All three devices look identical to the current versions but swap out their processors for the company’s first M5 chip, which provides improvements to computing speeds, graphics and artificial intelligence tasks, the company said.
- The entry prices for each product remain the same, with the iPad Pro starting at US$999 (from RM4,499 locally), the MacBook Pro coming in at US$1,599 (from RM6,999 locally), and the Vision Pro headset remaining US$3,499 (RM14,792).
- The iPad Pro also gains the company’s in-house N1 wireless chip and C1X modem, while the Vision Pro adds a new headband.
- iPad Pro Apple said that the AI performance in the M5 iPad Pro bests the M4 version by times.

======================
Event ID: 8
======================
- In March, Airbnb announced that, starting April 30, the company would ban the use of surveillance cameras in its rentals.
- “Cameras are both creepy and a threat,” said Albert Fox Cahn, the executive director of the Surveillance Technology Oversight Project, which has campaigned for a ban on cameras in Airbnbs since 2022.
- “People are terrified about having their intimate moments photographed without their consent and having owners able to monitor their activities within a For many travellers, Airbnb’s new policy has prompted some fundamental questions: What were the cameras doing there in the first place?
- And what are travellers’ rights when it comes to privacy in hotels and rental homes?
- Public use of cameras Cameras, of course, are everywhere in public life, from the self-checkout kiosks at big-box retailers to airport terminals.

======================
Event ID: 9
======================
- With the advent of consumer neurotechnologies, the data being collected is becoming ever more intimate.
- The new law, which passed by a 61-1 vote in the Colorado House and a 34-0 vote in the Senate, expands the definition of “sensitive data” in the state’s current personal privacy law to include biological and “neural data” generated by the brain, the spinal cord and the network of nerves that relays messages throughout the body.
- “What we think and feel, and the ability to decode that from the human brain, couldn’t be any more intrusive or personal to “We are really excited to have an actual bill signed into law that will protect people’s biological and neurological data,” said Rep
- I’m just really pleased about this The law takes aim at consumer-level brain technologies.
- Unlike sensitive patient data obtained from medical devices in clinical settings, which are protected by federal health law, the data surrounding consumer neurotechnologies go largely unregulated, Genser said.

## Pair-wise dataset preparation for fine-tuning

In [127]:
grouped = episode_df.groupby("event_id")

In [128]:
from itertools import combinations
import random

### Positive pair (Label:1)

In [129]:
positive_pairs = []

for event_id, group in grouped:
    sentences = group["sentence"].tolist()
    
    pairs = list(combinations(sentences, 2))
    pairs = random.sample(pairs, min(len(pairs), 70)) 
    
    for s1, s2 in pairs:
        positive_pairs.append((s1, s2, 1))

print(len(positive_pairs))

700

In [130]:
for i in range(3):
    pair_id = random.randint(0,len(positive_pairs))
    print("\n======================")
    print(f"Pair {pair_id}:")
    print("======================")
    print(positive_pairs[pair_id][0])
    print(positive_pairs[pair_id][1])

======================
Pair 514:
======================
Like its direct predecessor, the M5 iPad Pro has a thin design and includes a multilayered "tandem” OLED display - an approach that offers more brightness and efficiency
Since its release in early 2024, the Vision Pro has been viewed as too heavy and expensive

======================
Pair 94:
======================
I, for one, took this opportunity to disconnect my Roku TV from the Internet and plug in a different streaming device with less onerous terms, an old Apple TV.
But Roku is a bigger offender, as it collects much more information than it needs to provide a device that runs streaming apps, including information about your employment, education and religious beliefs, she said.

======================
Pair 291:
======================
The role played by 5G in this scenario comes largely in two areas.
He says with faster speeds and near-instant connectivity, 5G can support complex technologies like real-time holographic imaging.

### Negative pairs (Label:0)

In [131]:
negative_pairs = []

event_ids = list(grouped.groups.keys())

num_neg = len(positive_pairs)

for _ in range(num_neg):
    e1, e2 = random.sample(event_ids, 2)
    
    s1 = random.choice(grouped.get_group(e1)["sentence"].tolist())
    s2 = random.choice(grouped.get_group(e2)["sentence"].tolist())
    
    negative_pairs.append((s1, s2, 0))

print(len(negative_pairs))

700

In [135]:
for i in range(3):
    pair_id = random.randint(0,len(negative_pairs))
    print("\n======================")
    print(f"Pair {pair_id}:")
    print("======================")
    print(negative_pairs[pair_id][0])
    print(negative_pairs[pair_id][1])

======================
Pair 637:
======================
So he came up with a workaround to disconnect his Roku TV from the Internet and use it as a normal TV without Roku’s apps, which include Netflix, Hulu and other streaming services.
The company is still working on new AirPods hardware, including a third-generation version of the AirPods Pro.

======================
Pair 627:
======================
Supporters of the bill expressed their concern that neural data could be used to decode a person’s thoughts and feelings or to learn sensitive facts about an individual’s mental health, such as whether someone has epilepsy.
He also took the opportunity to showcase a fully functioning keyboard he crafted from Lego bricks.

======================
Pair 177:
======================
“The longer the eye, the more likely it is to have myopia,” she said.
In addition, Singapore Airlines and Thai Airways both prohibit the use or charging of portable power banks at all during flights.

### Combining the positive and negative pair

In [133]:
all_pairs = positive_pairs + negative_pairs

pairs_df = pd.DataFrame(all_pairs, columns=["sentence1", "sentence2", "label"])
pairs_df = pairs_df.sample(frac=1).reset_index(drop=True)

print(pairs_df.shape)
pairs_df.head()

(1400, 3)

,sentence1,sentence2,label
0,While Southwest is the first US airline to res...,"Until now, the AirPods Pro were all about keep...",0
1,The report analysed 30 consumer neurotechnolog...,While some eye doctors will give young childre...,0
2,With many consumers unwilling to splurge on a ...,"Mark Andrews, waste and recycling fires lead f...",0
3,The iPad Pro also gains the company’s in-house...,That company’s just-released Meta Ray-Ban Disp...,1
4,"If the bill passes, its legal implications wou...","For Bryan Lin, the advancement of technology b...",0

In [134]:
pairs_df.to_csv(r"dataset\fineTuned\pairwise_dataset.csv", index=False)