In [1]:
import pandas as pd

from sentence_transformers import InputExample
from sentence_transformers import SentenceTransformer

In [2]:
pairs_df = pd.read_csv("dataset/fineTuned/pairwise_dataset.csv")

print(pairs_df.shape)
pairs_df.head()

(1400, 3)

,sentence1,sentence2,label
0,While Southwest is the first US airline to res...,"Until now, the AirPods Pro were all about keep...",0
1,The report analysed 30 consumer neurotechnolog...,While some eye doctors will give young childre...,0
2,With many consumers unwilling to splurge on a ...,"Mark Andrews, waste and recycling fires lead f...",0
3,The iPad Pro also gains the company’s in-house...,That company’s just-released Meta Ray-Ban Disp...,1
4,"If the bill passes, its legal implications wou...","For Bryan Lin, the advancement of technology b...",0

In [3]:
train_examples = []

for _, row in pairs_df.iterrows():
    train_examples.append(
        InputExample(
            texts=[row["sentence1"], row["sentence2"]],
            label=float(row["label"])
        )
    )

print("Total training examples:", len(train_examples))

Total training examples: 1400

In [4]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [5]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=16)

In [6]:
from sentence_transformers import losses

train_loss = losses.CosineSimilarityLoss(model)

In [7]:
model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=3,
    warmup_steps=100,
    show_progress_bar=True
)

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

In [8]:
model.save(r"model\fine_tuned_minilm")