In [59]:
import pandas as pd
import re

In [60]:
file_name = "bitcoin_articles.csv"
df = pd.read_csv(file_name)
df.shape

(2500, 17)

In [61]:
df.head()

,article_id,title,author,published_date,link,clean_url,excerpt,summary,rights,article_rank,topic,country,language,authors,media,twitter_account,article_score
0,57a00c1140cbd3af79e77bf0e4e6af48,62% of Bitcoin Has Not Moved in a Year as Long...,Jamie McNeill,04-10-2022 17:15,https://www.business2community.com/crypto-news...,business2community.com,"Over the course of the last few years, there h...","Over the course of the last few years, there h...",business2community.com,1595,finance,US,en,Jamie McNeill,https://www.business2community.com/wp-content/...,@Jamie_DeFi,8.556426
1,21b48b3731c03466be3fac4be6c7dc67,The Orange Party Issue Playlist,Bitcoin Magazine,05-10-2022 21:17,https://bitcoinmagazine.com/culture/orange-par...,bitcoinmagazine.com,News Links: Russia Legalizing Bitcoin And Cryp...,Russia Legalizing Bitcoin And Crypto Is A Matt...,bitcoinmagazine.com,6284,news,US,en,Bitcoin Magazine,https://bitcoinmagazine.com/.image/t_share/MTk...,NaN,8.507881
2,77030740ee160ad68c25e4e63515dd77,How Many Bitcoins Are There?,AOL Staff,04-10-2022 21:44,https://www.gobankingrates.com/investing/crypt...,gobankingrates.com,Bitcoin has a maximum supply of 21 million. Ho...,Bitcoin has a maximum supply of 21 million. Ho...,aol.com,5044,news,US,en,"AOL Staff,David Granahan",https://s.yimg.com/ny/api/res/1.2/wPK4V8gjwjrD...,@AOL,8.483973
3,19285dde79599b6a9b4aa5a58805159b,Bitcoin 2008–2022: From Bouncing Baby To Troub...,Mark Hooson,03-10-2022 15:45,https://www.forbes.com/advisor/au/investing/bi...,forbes.com,"Conceived in 2008 and launched in 2009, bitcoi...","Conceived in 2008 and launched in 2009, bitcoi...",forbes.com,49,business,US,en,"Forbes Staff,Kevin Pratt,Mark Hooson,Sophie Venz",https://thumbor.forbes.com/thumbor/fit-in/x/ht...,NaN,8.466393
4,ad1822c7ff1bbd7e38f7f9dbdbce245f,"Bitcoin Lightning Network capacity strikes 5,0...",Joseph Hall,03-10-2022 12:09,https://cointelegraph.com/news/bitcoin-lightni...,cointelegraph.com,"First created in 2018, the Lighting Network ha...",Bear markets are for building out capacity on ...,cointelegraph.com,1696,news,US,en,Joseph Hall,https://images.cointelegraph.com/images/1200_a...,@cointelegraph,8.446906

In [62]:
df.columns

Index(['article_id', 'title', 'author', 'published_date', 'link', 'clean_url',
       'excerpt', 'summary', 'rights', 'article_rank', 'topic', 'country',
       'language', 'authors', 'media', 'twitter_account', 'article_score'],
      dtype='object')

In [63]:
data = df[['summary','title']]
data.head()

,summary,title
0,"Over the course of the last few years, there h...",62% of Bitcoin Has Not Moved in a Year as Long...
1,Russia Legalizing Bitcoin And Crypto Is A Matt...,The Orange Party Issue Playlist
2,Bitcoin has a maximum supply of 21 million. Ho...,How Many Bitcoins Are There?
3,"Conceived in 2008 and launched in 2009, bitcoi...",Bitcoin 2008–2022: From Bouncing Baby To Troub...
4,Bear markets are for building out capacity on ...,"Bitcoin Lightning Network capacity strikes 5,0..."

In [64]:
data.shape

(2500, 2)

## Preprocessing

In [65]:
data = data.dropna()

In [66]:
data.title.isna().sum()

0

In [69]:
data = data.copy()
data.summary = (
    data.summary
    .str.lower()
    .str.replace(r'\n','',regex=True)
    .str.replace(r'[^a-z0-9\%]',' ',regex=True)
)
data.title = (
    data.title
    .str.lower()
    .str.replace(r'\n','',regex=True)
    .str.replace(r'[^a-z0-9\%]',' ',regex=True)
)

data.head()

,summary,title
0,over the course of the last few years there h...,62% of bitcoin has not moved in a year as long...
1,russia legalizing bitcoin and crypto is a matt...,the orange party issue playlist
2,bitcoin has a maximum supply of 21 million ho...,how many bitcoins are there
3,conceived in 2008 and launched in 2009 bitcoi...,bitcoin 2008 2022 from bouncing baby to troub...
4,bear markets are for building out capacity on ...,bitcoin lightning network capacity strikes 5 0...